version: '3'

services:
  backend:
    build:
      context: ./backend
    env_file:
    - ./backend/.env
    ports:
    - 8082:8082
    volumes:
      - ./backend:/app
    command: go run main.go
  
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    command: /bin/sh -c "npm install && npm run build"

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=kolasf0963
      - POSTGRES_PASSWORD=0963aLeX$
      - POSTGRES_DB=koloksha_orders
    ports:
      - 5435:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt  # Монтируем только сертификаты
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html
    environment:
      - NGINX_HOST=koloksha.ru
      - NGINX_EMAIL=amel0820@mail.ru
    depends_on:
      - backend
      - frontend

volumes:
  postgres-db:
